### ISSUE TITLE
License

### ISSUE THREAD

**Issue by papa-zulu** [gerasimvol/vue-prlx#1]
Hi Vladimir,

Thanks for creating such an amazing VueJs plugin :)

Do you mind including a license file to your repository or do you prefer to keep it copyrighted?
I saw that you have published it under MIT license on [npm.org](https://www.npmjs.com/package/vue-prlx), but there is no license file in Github repository.

Regards

**Comment by gerasimvol** [comment]
@papa-zulu done 👌
