### ISSUE TITLE
Question: How I can use the mobile and background modifier at the same time?

### ISSUE THREAD

**Issue by albertbenitez** [gerasimvol/vue-prlx#6]
Hello,
I'm trying to have the **mobile** and **background** **modifiers** at the same element. How can I do it?
I tried:
```
<div  v-prlx.mobile v-prlx.background="{ speed: 0.12}"></div>
<div  v-prlx.mobile.background="{ speed: 0.12}"></div>
<div  v-prlx.mobile v-prlx.background="{ speed: 0.12,  mobile: true }"></div>
```
But no luck. Any ideas on how to do it?
@gerasimvol

**Comment by albertbenitez** [comment]
Does anyone have a clue? 😬
Should I modify the source code in order to do that?

**Comment by gerasimvol** [comment]
@albertbenitez `v-prlx.mobile.background="{ speed: 0.12}"` worked fine for me
https://github.com/gerasimvol/vue-prlx/tree/master/example
